import java.nio.charset.Charset;

/** Run: java scripts/encoding/GenerateJavaCharsets.java > src/JavaCharsetData.h
 * Tables are the JDK charset mappings used by jbms-parser (OpenJDK 25).
 * Each entry packs the decoded BMP character and the number (0..2) of
 * original bytes preserved by Java's decode/encode round trip. Bit 18 marks
 * malformed pairs whose second byte must be decoded separately.
 */
class GenerateJavaCharsets {
    public static void main(String[] args) {
        System.out.println("// Generated by scripts/encoding/GenerateJavaCharsets.java (OpenJDK 25).\n#pragma once\n#include <cstdint>\nnamespace bms_parser::detail {");
        for (String name : new String[]{"EUC-KR", "MS932"}) {
            Charset charset = Charset.forName(name);
            System.out.println("constexpr uint32_t " + (name.equals("MS932") ? "kMs932Pairs" : "kJavaEucKrPairs") + "[] = {");
            int column = 0;
            for (int first = 0x81; first <= 0xfe; first++) {
                if (name.equals("MS932") ? !(first <= 0x9f || first >= 0xe0 && first <= 0xfc) : first < 0xa1) continue;
                int low = name.equals("MS932") ? 0x40 : 0xa1;
                int high = name.equals("MS932") ? 0xfc : 0xfe;
                for (int second = low; second <= high; second++) {
                    byte[] bytes = {(byte)first, (byte)second};
                    String decoded = new String(bytes, charset);
                    int cp = decoded.charAt(0);
                    byte[] encoded = decoded.getBytes(charset);
                    int match = 0;
                    while (match < Math.min(2, encoded.length) && bytes[match] == encoded[match]) match++;
                    int packed = cp | match << 16 | (decoded.length() > 1 ? 1 << 18 : 0);
                    System.out.printf("%s0x%05x,", column % 12 == 0 ? "" : " ", packed);
                    if (++column % 12 == 0) System.out.println();
                }
            }
            if (column % 12 != 0) System.out.println();
            System.out.println("};");
            System.out.println("constexpr unsigned char " + (name.equals("MS932") ? "kMs932InvalidPairLength" : "kEucKrInvalidPairLength") + "[] = {");
            for (int first = 0; first < 256; first++) {
                String decoded = new String(new byte[]{(byte)first, (byte)0xff}, charset);
                System.out.print((decoded.length() == 1 ? 2 : 1) + (first % 32 == 31 ? ",\n" : ", "));
            }
            System.out.println("};");
        }
        System.out.println("} // namespace bms_parser::detail");
    }
}
